### ISSUE TITLE
suggestion: Change title color

### ISSUE THREAD

**Issue by 2334o** [actionscourc/github-crash-course#2]
I think it looks better if the main title is a bit more orange.

The styling rule could be changed like this:

``` css
h1 {
  color: #f39e0c;
}
```
